# Generated by Django 5.1.1 on 2024-10-02 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesinfo',
            name='products',
        ),
        migrations.AlterModelTable(
            name='sales',
            table=None,
        ),
        migrations.AlterModelTable(
            name='salesinfo',
            table=None,
        ),
        migrations.AddField(
            model_name='salesinfo',
            name='products',
            field=models.ManyToManyField(to='products.product'),
        ),
    ]
