# apps/clients/choices.py

DISTRICT_CHOICES = [
    # Lima Metropolitana
    ('Ancón', 'Ancón'),
    ('Ate', 'Ate'),
    ('Barranco', 'Barranco'),
    ('Breña', 'Breña'),
    ('Carabayllo', 'Carabayllo'),
    ('Chaclacayo', 'Chaclacayo'),
    ('Chorrillos', 'Chorrillos'),
    ('Cieneguilla', 'Cieneguilla'),
    ('Comas', 'Comas'),
    ('El Agustino', 'El Agustino'),
    ('Independencia', 'Independencia'),
    ('Jesús María', 'Jesús María'),
    ('La Molina', 'La Molina'),
    ('La Victoria', 'La Victoria'),
    ('Lince', 'Lince'),
    ('Los Olivos', 'Los Olivos'),
    ('Lurigancho', 'Lurigancho'),
    ('Lurín', 'Lurín'),
    ('Magdalena del Mar', 'Magdalena del Mar'),
    ('Miraflores', 'Miraflores'),
    ('Pachacamac', 'Pachacamac'),
    ('Pucusana', 'Pucusana'),
    ('Pueblo Libre', 'Pueblo Libre'),
    ('Puente Piedra', 'Puente Piedra'),
    ('Punta Hermosa', 'Punta Hermosa'),
    ('Punta Negra', 'Punta Negra'),
    ('Rímac', 'Rímac'),
    ('San Bartolo', 'San Bartolo'),
    ('San Borja', 'San Borja'),
    ('San Isidro', 'San Isidro'),
    ('San Juan de Lurigancho', 'San Juan de Lurigancho'),
    ('San Juan de Miraflores', 'San Juan de Miraflores'),
    ('San Luis', 'San Luis'),
    ('San Martín de Porres', 'San Martín de Porres'),
    ('San Miguel', 'San Miguel'),
    ('Santa Anita', 'Santa Anita'),
    ('Santa María del Mar', 'Santa María del Mar'),
    ('Santa Rosa', 'Santa Rosa'),
    ('Santiago de Surco', 'Santiago de Surco'),
    ('Surquillo', 'Surquillo'),
    ('Villa El Salvador', 'Villa El Salvador'),
    ('Villa María del Triunfo', 'Villa María del Triunfo'),

    # Callao
    ('Callao', 'Callao'),
    ('Bellavista', 'Bellavista'),
    ('Carmen de La Legua Reynoso', 'Carmen de La Legua Reynoso'),
    ('La Perla', 'La Perla'),
    ('La Punta', 'La Punta'),
    ('Ventanilla', 'Ventanilla'),
    ('Mi Perú', 'Mi Perú'),
]
