# Generated by Django 5.1.1 on 2024-09-28 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
    ]
