# Generated by Django 5.1.1 on 2024-10-01 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='clients',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
