# Generated by Django 5.1.1 on 2024-10-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_lat_clients_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='references',
            field=models.TextField(blank=True, null=True),
        ),
    ]
