# Generated by Django 5.1.1 on 2024-09-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_birthday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='name',
            new_name='first_name',
        ),
    ]
