# Generated by Django 5.1.1 on 2024-09-28 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_rename_name_clients_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clients',
            old_name='first_name',
            new_name='firstname',
        ),
    ]
